### ISSUE TITLE
trace.modname does not exist since Python 3.2

### ISSUE THREAD

**Issue by alecxe** [fabioz/PyDev.Debugger#69]
Linking the [StackOverflow post](http://stackoverflow.com/questions/41108931/module-trace-has-no-attribute-modname-while-trying-to-debug-in-pycharm-pyth/41373236#41373236) which initially caught this problem.

The problem is that if the PyCharm debugger would be started with `--save-signatures` ("Collect run-time types information for code insight" Python Debugger setting), it would fail with:

> AttributeError: module 'trace' has no attribute 'modname'

The problem is on [this line](https://github.com/fabioz/PyDev.Debugger/blob/pycharm/pydevd_signature.py#L68):

```
modulename = trace.modname(filename)
```

There is no `modname` function in the `trace` module since Python 3.2. There is `_modname` now.

Please fix. Let me know if you have any further questions.

Reproduced using PyCharm 2016.3.1 and Python 3.6.

**Comment by Salsapareille** [comment]
I got exactly the same.
Reproduced using PyCharm 2016.3.2 and Python 3.6

**Comment by PeterZhizhin** [comment]
I have exactly the same problem while trying to enable "Collect run-time types information for code insight".
The PyCharm version is:

```
PyCharm 2016.3.3
Build #PY-163.15188.4, built on March 10, 2017
Subscription is active until September 10, 2017
JRE: 1.8.0_112-release-408-b6 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```

**Comment by ajurna** [comment]
I also have this issue PyCharm 2016.3.3 and Python 3.6.0

**Comment by s-slattery** [comment]
same issue here. When is a fix expected?

**Comment by fabioz** [comment]
Well, it's all open source and it should be a simple fix... (mostly seeing what modname did and recreate that function internally if it's not available) does someone volunteer to fix it locally/test and provide a pull request?

**Comment by oechslein** [comment]
For me it works in 2017.1 RC2 (https://www.jetbrains.com/pycharm/nextversion/)!
