### ISSUE TITLE
Debugger fail to import from Qt

### ISSUE THREAD

**Issue by trofimander** [fabioz/PyDev.Debugger#21]
Original issue with attached project: https://youtrack.jetbrains.com/issue/PY-13975

Running the following code in PyCharm 4.0 EAP 138.2401 

```
from PyQt5.Qt import QT_VERSION_STR
print(QT_VERSION_STR)
```

cause

```
/Users/Alex/.virtualenvs/py3dev/bin/python "/Applications/PyCharm 4.0 EAP.app/Contents/helpers/pydev/pydevd.py" --multiproc --save-signatures --client 127.0.0.1 --port 52578 --file /Users/Alex/Workspace/bugbug/main.py
pydev debugger: process 2024 is connecting

Connected to pydev debugger (build null)
Traceback (most recent call last):
  File "/Applications/PyCharm 4.0 EAP.app/Contents/helpers/pydev/pydevd.py", line 2145, in <module>
    globals = debugger.run(setup['file'], None, None)
  File "/Applications/PyCharm 4.0 EAP.app/Contents/helpers/pydev/pydevd.py", line 1584, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm 4.0 EAP.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc) 
  File "/Users/Alex/Workspace/bugbug/main.py", line 3, in <module>
    from PyQt5.Qt import QT_VERSION_STR
ImportError: cannot import name 'QT_VERSION_STR'
```

Just running the script works fine. Same test code works fine in PyCharm 3.4.1 153.1057 debugger.

Here the output of the PyCharm log file.

```
java.lang.Throwable
    at com.intellij.openapi.diagnostic.Logger.error(Logger.java:115)
    at com.jetbrains.python.debugger.pydev.RemoteDebugger$DebuggerReader.processResponse(RemoteDebugger.java:504)
    at com.jetbrains.python.debugger.pydev.RemoteDebugger$DebuggerReader.onTextAvailable(RemoteDebugger.java:606)
    at com.intellij.util.io.BaseOutputReader.readAvailable(BaseOutputReader.java:74)
    at com.jetbrains.python.debugger.pydev.RemoteDebugger$DebuggerReader.doRun(RemoteDebugger.java:467)
    at com.intellij.util.io.BaseDataReader$1.run(BaseDataReader.java:46)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:405)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
    at java.lang.Thread.run(Thread.java:695)
    at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)
2014-09-23 10:30:33,519 [ 448967]  ERROR - on.pydev.remote.RemoteDebugger - PyCharm PY-138.2401  Build #PY-138.2401 
2014-09-23 10:30:33,519 [ 448967]  ERROR - on.pydev.remote.RemoteDebugger - JDK: 1.6.0_65 
2014-09-23 10:30:33,519 [ 448967]  ERROR - on.pydev.remote.RemoteDebugger - VM: Java HotSpot(TM) 64-Bit Server VM 
2014-09-23 10:30:33,519 [ 448967]  ERROR - on.pydev.remote.RemoteDebugger - Vendor: Apple Inc. 
2014-09-23 10:30:33,519 [ 448967]  ERROR - on.pydev.remote.RemoteDebugger - OS: Mac OS X 
2014-09-23 10:30:33,519 [ 448967]  ERROR - on.pydev.remote.RemoteDebugger - Last Action: Rerun 
2014-09-23 10:30:33,520 [ 448968]  ERROR - on.pydev.remote.RemoteDebugger - Error response from debugger: Error evaluating expression Traceback (most recent call last):
  File "/Applications/PyCharm 4.0 EAP.app/Contents/helpers/pydev/pydevd_vars.py", line 303, in evaluateExpression
    compiled = compile(expression, '<string>', 'eval')
  File "<string>", line 1
    from PyQt5.Qt import QT_VERSION_STR
       ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/PyCharm 4.0 EAP.app/Contents/helpers/pydev/pydevd_comm.py", line 1032, in doIt
    result = pydevd_vars.evaluateExpression(self.thread_id, self.frame_id, self.expression, self.doExec)
  File "/Applications/PyCharm 4.0 EAP.app/Contents/helpers/pydev/pydevd_vars.py", line 305, in evaluateExpression
    Exec(expression, updated_globals, frame.f_locals)
  File "/Applications/PyCharm 4.0 EAP.app/Contents/helpers/pydev/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<string>", line 1, in <module>
ImportError: cannot import name 'QT_VERSION_STR'


java.lang.Throwable
    at com.intellij.openapi.diagnostic.Logger.error(Logger.java:115)
    at com.jetbrains.python.debugger.pydev.RemoteDebugger$DebuggerReader.processResponse(RemoteDebugger.java:504)
    at com.jetbrains.python.debugger.pydev.RemoteDebugger$DebuggerReader.onTextAvailable(RemoteDebugger.java:606)
    at com.intellij.util.io.BaseOutputReader.readAvailable(BaseOutputReader.java:74)
    at com.jetbrains.python.debugger.pydev.RemoteDebugger$DebuggerReader.doRun(RemoteDebugger.java:467)
    at com.intellij.util.io.BaseDataReader$1.run(BaseDataReader.java:46)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:405)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
    at java.lang.Thread.run(Thread.java:695)
    at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)
2014-09-23 10:30:33,520 [ 448968]  ERROR - on.pydev.remote.RemoteDebugger - PyCharm PY-138.2401  Build #PY-138.2401 
2014-09-23 10:30:33,520 [ 448968]  ERROR - on.pydev.remote.RemoteDebugger - JDK: 1.6.0_65 
2014-09-23 10:30:33,520 [ 448968]  ERROR - on.pydev.remote.RemoteDebugger - VM: Java HotSpot(TM) 64-Bit Server VM 
2014-09-23 10:30:33,520 [ 448968]  ERROR - on.pydev.remote.RemoteDebugger - Vendor: Apple Inc. 
2014-09-23 10:30:33,520 [ 448968]  ERROR - on.pydev.remote.RemoteDebugger - OS: Mac OS X 
2014-09-23 10:30:33,520 [ 448968]  ERROR - on.pydev.remote.RemoteDebugger - Last Action: Rerun 
2014-09-23 10:37:51,380 [ 886828]   INFO - ij.components.ComponentManager - com.intellij.openapi.project.impl.ProjectReloadStateImpl initialized in 12 ms 
2014-09-23 10:37:51,447 [ 886895]   INFO - ellij.project.impl.ProjectImpl - 118 project components initialized in 90 ms 
2014-09-23 10:37:51,453 [ 886901]   INFO - le.impl.ModuleManagerComponent - 1 module(s) loaded in 6 ms 
2014-09-23 10:37:51,803 [ 887251]   INFO - indexing.UnindexedFilesUpdater - Indexable files iterated in 5 ms 
2014-09-23 10:37:51,803 [ 887251]   INFO - indexing.UnindexedFilesUpdater - Unindexed files update started: 1 files to update 
2014-09-23 10:37:51,808 [ 887256]   INFO - indexing.UnindexedFilesUpdater - Unindexed files update done in 5 ms 
2014-09-23 10:37:53,079 [ 888527]   INFO - tor.impl.FileEditorManagerImpl - Project opening took 1729 ms 
```

Please find attached the demo project.

Regards,
Alex
